apiVersion: v1
kind: Namespace
metadata:
  name: staging 
---
kind: Service
apiVersion: v1
metadata:
  name: k8s-demo
  namespace: staging
spec:
  ports:
  - protocol: TCP
    port: 8888
    targetPort: ui
  selector:
    k8s-app: k8s-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: staging
spec:
  selector:
      matchLabels:
        app: k8s-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
        - name: k8s-demo
          image: halfback/k8s-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
          - name: commit_id 
            value: latest 
